"""Sakshi: a metacognitive runtime for Python agents."""

from __future__ import annotations

from sakshi.cycle import (
    LastNPruner,
    SinceAnomalyPruner,
    TracePruner,
    WhereExpectationFiredPruner,
)
from sakshi.errors import (
    AnomalyEscalationError,
    GoalValidationError,
    PhaseTransitionError,
    PlanSoundnessError,
    SakshiError,
    WorldStateUnavailableError,
)
from sakshi.goals import (
    AcceptingRebelHook,
    RebelDecision,
    RebelHook,
    RebelVerdict,
)
from sakshi.interpret import (
    CalibrationReport,
    CalibrationTracker,
    CalibrationWarning,
    ConfidenceObservation,
    GoalLineageAuditor,
    LineageReport,
    LineageVerdict,
    TRAPDimension,
    TRAPRouter,
    classify_failure_mode,
)
from sakshi.meta import (
    AlwaysPermitPolicy,
    CanalizationMetrics,
    CanalizationRisk,
    DeliberationDecision,
    DeliberationGate,
    DeliberationPath,
    EveryCyclePolicy,
    InterventionDecision,
    InterventionExecutor,
    InterventionOutcome,
    InterventionPermissionPolicy,
    InterventionRecord,
    InterventionType,
    MetaSchedulingPolicy,
    OnAnomalyPolicy,
    SchedulingDecision,
    ThrottledByLoadPolicy,
)
from sakshi.models import (
    AnomalySourceType,
    DiscrepancyResolution,
    ExpectationProfile,
    FailureMode,
    GoalEvent,
    GoalEventType,
    GoalMode,
    GoalOperation,
    GoalOperationEvent,
    ProjectionTransparency,
    ReasoningTransparency,
    ResolutionLevel,
    StatusTransparency,
    TransparencyLevel,
)
from sakshi.plans import (
    Action,
    AnticipatoryRiskScorer,
    GoalConstraint,
    PlanRisk,
    PlanRiskAssessment,
    RiskBand,
    RiskModel,
    TaskDecomposer,
)
from sakshi.protocols import (
    AlwaysPermitWriteGuard,
    BasinHook,
    Clock,
    EventBus,
    GoalStateStore,
    NoOpBasinHook,
    NoOpEventBus,
    WriteGuard,
)
from sakshi.registries import PhaseRegistry

__version__ = "0.6.0a0"

__all__ = [
    "AcceptingRebelHook",
    "Action",
    "AlwaysPermitPolicy",
    "AlwaysPermitWriteGuard",
    "AnomalyEscalationError",
    "AnomalySourceType",
    "AnticipatoryRiskScorer",
    "BasinHook",
    "CalibrationReport",
    "CalibrationTracker",
    "CalibrationWarning",
    "CanalizationMetrics",
    "CanalizationRisk",
    "Clock",
    "ConfidenceObservation",
    "DeliberationDecision",
    "DeliberationGate",
    "DeliberationPath",
    "DiscrepancyResolution",
    "EventBus",
    "EveryCyclePolicy",
    "ExpectationProfile",
    "FailureMode",
    "GoalConstraint",
    "GoalEvent",
    "GoalEventType",
    "GoalLineageAuditor",
    "GoalMode",
    "GoalOperation",
    "GoalOperationEvent",
    "GoalStateStore",
    "GoalValidationError",
    "InterventionDecision",
    "InterventionExecutor",
    "InterventionOutcome",
    "InterventionPermissionPolicy",
    "InterventionRecord",
    "InterventionType",
    "LastNPruner",
    "LineageReport",
    "LineageVerdict",
    "MetaSchedulingPolicy",
    "NoOpBasinHook",
    "NoOpEventBus",
    "OnAnomalyPolicy",
    "PhaseRegistry",
    "PhaseTransitionError",
    "PlanRisk",
    "PlanRiskAssessment",
    "PlanSoundnessError",
    "ProjectionTransparency",
    "ReasoningTransparency",
    "RebelDecision",
    "RebelHook",
    "RebelVerdict",
    "ResolutionLevel",
    "RiskBand",
    "RiskModel",
    "SakshiError",
    "SchedulingDecision",
    "SinceAnomalyPruner",
    "StatusTransparency",
    "TRAPDimension",
    "TRAPRouter",
    "TaskDecomposer",
    "ThrottledByLoadPolicy",
    "TracePruner",
    "TransparencyLevel",
    "WhereExpectationFiredPruner",
    "WorldStateUnavailableError",
    "WriteGuard",
    "__version__",
    "classify_failure_mode",
]
